#!/bin/sh

# versionpkg - a makepkg wrapper for building CVS/SVN pkgs
# dibblethewrecker.at.jiwe.org

# makepkg configuration
[ -f /etc/makepkg.conf ] && source /etc/makepkg.conf

# SUBROUTINES
plain() {
	if [ "$USE_COLOR" = "Y" -o "$USE_COLOR" = "y" ]; then
		echo -e "    \033[1;1m$1\033[1;0m" >&2
	else
		echo "    $1" >&2
	fi
}
msg() {
	if [ "$USE_COLOR" = "Y" -o "$USE_COLOR" = "y" ]; then
		echo -e "\033[1;32m==>\033[1;0m \033[1;1m$1\033[1;0m" >&2
	else
		echo "==> $1" >&2
	fi
}
warning() {
	if [ "$USE_COLOR" = "Y" -o "$USE_COLOR" = "y" ]; then
		echo -e "\033[1;33m==> WARNING:\033[1;0m \033[1;1m$1\033[1;0m" >&2
	else
		echo "==> WARNING: $1" >&2
	fi
}
error() {
	if [ "$USE_COLOR" = "Y" -o "$USE_COLOR" = "y" ]; then
		echo -e "\033[1;31m==> ERROR:\033[1;0m \033[1;1m$1\033[1;0m" >&2
	else
		echo "==> ERROR: $1" >&2
	fi
}

source PKGBUILD
oldpkgver=$pkgver

if [ ! -z ${_cvsroot} ] && [ ! -z ${_cvsmod} ] ; then
	cvsdate=`date +%Y%m%d`
	sed -i "1,11 s|pkgver=$oldpkgver|pkgver=$cvsdate|" ./PKGBUILD
	makepkg $@
	if [ $? -gt 0 ] ; then
		error "Reverting pkgver..."
		sed -i "1,11 s|pkgver=$cvsdate|pkgver=$oldpkgver|" ./PKGBUILD
	fi     	
elif [ ! -z ${_svntrunk} ] && [ ! -z ${_svnmod} ] ; then
	svnrevno=`svn log $_svntrunk --limit 1 | grep -m 1 -o "r.*" | cut -d \| -f 1 | sed s@r@@g`
	msg "Current revision number is $svnrevno"
	if [ "${1}" != "-f" ] && [ "${oldpkgver}" == "${svnrevno}" ] ; then
		error "No new revision available.  (use -f to overwrite)"
		exit
	fi
	sleep 3
	sed -i "1,11 s|pkgver=$oldpkgver|pkgver=$svnrevno|" ./PKGBUILD
	makepkg $@
	if [ $? -gt 0 ] ; then
		error "Reverting pkgver..."
		sed -i "1,11 s|pkgver=$svnrevno|pkgver=$oldpkgver|" ./PKGBUILD
	fi 
else
	error "No SVN or CVS variables found! Aborting..."
	exit
fi
